components:
  schemas:
    CommandTypes:
      $id: CommandTypes
      type: string
      enum: # This is the most supported way to define a specific string as the only valid input. `const` is a new keyword which is supported in OpenAPI, but not in all corresponding codegen tools. https://github.com/OAI/OpenAPI-Specification/issues/1313
        - account_channels
        - account_info
        - submit
        - account_lines
        - server_info

    ResponseWarning:
      $id: ResponseWarning
      type: object
      description: Used to share rate-limiting warnings or other potential issues with a request.
      properties:
        details:
          type: object
          additionalProperties:
            type: string
          description: Additional information about this warning. The contents vary depending on the type of warning.
        id:
          type: integer
          description: A unique numeric code for this warning message.
        message:
          type: string
          description: >
            A human-readable string describing the cause of this message.
            Do not write software that relies the contents of this message;
            use the id (and details, if applicable) to identify the warning instead.
      required:
        - id
        - message

    BaseRequest:
      $id: BaseRequest
      type: object
      description: Information which could be included in every request sent to rippled
      properties:
        api_version:
          type: integer
          description: The API version to use. If omitted, uses version 1.

    BaseSuccessResponse:
      $id: BaseSuccessResponse
      type: object
      description: Information which is included in every successful response from a request sent to rippled.
      properties:
        forwarded:
          type: boolean
          description: Indicates whether the request was forwarded.
        status:
          type: string
          description: The status of the response (e.g., 'success').
          enum:
            - success
        warning:
          type: string
          description: A specific warning type (e.g., 'load').
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/ResponseWarning'
          description: An array of response warnings.
      required:
        - status

    LookupByLedgerRequest:
      $id: LookupByLedgerRequest
      type: object
      description: Additional information shared in requests which search for specific ledger data.
      properties:
        ledger_hash:
          type: string
          format: hash256
          description: A 20-byte hex string for the ledger version to use.
        ledger_index:
          oneOf:
            - type: string
            - type: integer
          description: The ledger index of the ledger to use, or a shortcut string.

    WebsocketErrorFields:
      $id: WebsocketErrorFields
      type: object
      properties:
        api_version:
          type: integer
          description: The api_version specified in the request, if any.

    UniversalErrorResponseCodes:
      $id: UniversalErrorResponseCodes
      enum:
        - amendmentBlocked
        - failedToForward
        - invalid_API_version
        - noClosed
        - noCurrent
        - noNetwork
        - tooBusy
        - unknownCmd
    x-enum-descriptions:
      amendmentBlocked: The server is amendment blocked and needs to be updated to the latest version to stay synced with the XRP Ledger network.
      failedToForward: (Reporting Mode servers only) The server tried to forward this request to a P2P Mode server, but the connection failed.
      invalid_API_version: The server does not support the API version number from the request.
      noClosed: The server does not have a closed ledger, typically because it has not finished starting up.
      noCurrent: The server does not know what the current ledger is, due to high load, network problems, validator failures, incorrect configuration, or some other problem.
      noNetwork: The server is having trouble connecting to the rest of the XRP Ledger peer-to-peer network (and is not running in stand-alone mode).
      tooBusy: The server is under too much load to do this command right now. Generally not returned if you are connected as an admin.
      unknownCmd: The request does not contain a command that the rippled server recognizes.

    BaseTransaction:
      $id: BaseTransaction
      type: object
      required:
        - Account
        - TransactionType
      properties:
        Account:
          type: string
          description: The unique address of the account that initiated the transaction.
          x-custom-validation:
            isAccount: true
        TransactionType:
          type: string
          description: >
            The type of transaction. Valid transaction types include: Payment, OfferCreate, TrustSet, and many others.
        Fee:
          type: string
          description: Integer amount of XRP, in drops, to be destroyed as a cost for distributing this transaction to the network. Some transaction types have different minimum requirements. See Transaction Cost for details.
        Sequence:
          type: integer
          format: uint32
          description: The sequence number of the account sending the transaction. A transaction is only valid if the Sequence number is exactly 1 greater than the previous transaction from the same account. The special case 0 means the transaction is using a Ticket instead.
        AccountTxnID:
          type: string
          description: Hash value identifying another transaction. If provided, this transaction is only valid if the sending account's previously-sent transaction matches the provided hash.
        Flags:
          type: integer
          format: uint32
          description: Set of bit-flags for this transaction.
        LastLedgerSequence:
          type: integer
          format: uint32
          description: Highest ledger index this transaction can appear in. Specifying this field places a strict upper limit on how long the transaction can wait to be validated or rejected.
        Memos:
          type: array
          items:
            $ref: '#/components/schemas/Memo'
          description: The Memos field includes arbitrary messaging data with the transaction. It is presented as an array of objects. Each object has only one field, Memo, which in turn contains another object. The Memos field is limited to no more than 1 KB in size (when serialized in binary format). The MemoType and MemoFormat fields should only consist of the following characters - ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=%
          example:
            TransactionType: Payment
            Account: rMmTCjGFRWPz8S2zAUUoNVSQHxtRQD4eCx
            Destination: r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV
            Memos:
              - Memo:
                  MemoType: 687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963
                  MemoData: 72656e74
            Amount: '1'
        NetworkID:
          type: integer
          format: uint32
          description: The network ID of the chain this transaction is intended for. MUST BE OMITTED for Mainnet and some test networks. REQUIRED on chains whose network ID is 1025 or higher.
        Signers:
          type: array
          items:
            type: object
          description: Array of objects that represent a multi-signature which authorizes this transaction.
        SourceTag:
          type: integer
          format: uint32
          description: Arbitrary integer used to identify the reason for this payment, or a sender on whose behalf this transaction is made.
        SigningPubKey:
          type: string
          description: Hex representation of the public key that corresponds to the private key used to sign this transaction. If an empty string, indicates a multi-signature is present in the Signers field instead.
        TicketSequence:
          type: integer
          format: uint32
          description: The sequence number of the ticket to use in place of a Sequence number. If this is provided, Sequence must be 0. Cannot be used with AccountTxnID.
        TxnSignature:
          type: string
          description: The signature that verifies this transaction as originating from the account it says it is from.
        Delegate:
          type: string
          description: The delegated account that initiates and signs this transaction on behalf of the delegating account. If this field is present, the transaction must be signed by this delegated account. The Account field represents the delegating account, which is the actual account the transaction applies to. If the delegated account lacks the necessary permission, the transaction will fail.
          x-custom-validation:
            isAccount: true

    PseudoTransaction:
      $id: PseudoTransaction
      type: object
      required:
        - Account
        - TransactionType
      properties:
        Account:
          type: string
          description: The unique address of the account that initiated the transaction.
          x-custom-validation:
            isAccount: true
        TransactionType:
          type: string
          description: >
            The type of transaction. Valid transaction types include: Payment, OfferCreate, TrustSet, and many others.
        Fee:
          type: string
          description: Integer amount of XRP, in drops, to be destroyed as a cost for distributing this transaction to the network. Some transaction types have different minimum requirements. See Transaction Cost for details.
        Sequence:
          type: integer
          format: uint32
          description: The sequence number of the account sending the transaction. A transaction is only valid if the Sequence number is exactly 1 greater than the previous transaction from the same account. The special case 0 means the transaction is using a Ticket instead.
        Flags:
          type: integer
          format: uint32
          description: Set of bit-flags for this transaction.
        SigningPubKey:
          type: string
          description: Hex representation of the public key that corresponds to the private key used to sign this transaction. If an empty string, indicates a multi-signature is present in the Signers field instead.
        TxnSignature:
          type: string
          description: The signature that verifies this transaction as originating from the account it says it is from.

    Memo:
      type: object
      properties:
        MemoData:
          type: string
          description: Arbitrary hex value, conventionally containing the content of the memo.
        MemoFormat:
          type: string
          description: Hex value representing characters allowed in URLs. Conventionally containing information on how the memo is encoded, for example as a [MIME type](https://www.iana.org/assignments/media-types/media-types.xhtml).
        MemoType:
          type: string
          description: Hex value representing characters allowed in URLs. Conventionally, a unique relation (according to [RFC 5988](https://datatracker.ietf.org/doc/html/rfc5988#section-4)) that defines the format of this memo.

    TokenAmount:
      $id: TokenAmount
      type: object
      description: Specifies an amount of a (fungible) token.
      properties:
        currency:
          type: string
          description: 'Arbitrary currency code for the token. Cannot be XRP.'
        value:
          type: string
          pattern: '^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$'
          description: 'Quoted decimal representation of the amount of the token. This can include scientific notation, such as 1.23e11 meaning 123,000,000,000. Both e and E may be used. This can be negative when displaying balances, but negative values are disallowed in other contexts such as specifying how much to send.'
          x-custom-validation:
            isNumericString: true
        issuer:
          type: string
          description: 'Generally, the account that issues this token. In special cases, this can refer to the account that holds the token instead (for example, in a Clawback transaction).'
          x-custom-validation:
            isAccount: true

    Currency:
      $id: Currency
      description: |
        The XRP Ledger has two kinds of money: XRP, and issued currencies. Both types have high precision, although their
        formats are different.
      oneOf:
        - $ref: '#/components/schemas/XRP'
        - $ref: '#/components/schemas/IssuedCurrency'

    XRP:
      $id: XRP
      properties:
        currency:
          type: string
          description: ^
            Specifies XRP as a currency, without a value. Normally, you will not use this
            model as it does not specify an amount of XRP. In cases where you need to
            specify an amount of XRP, you will use a string. However, for some book order
            requests where currencies are specified without amounts, you may need to
            specify the use of XRP, without a value. In these cases, you will use this
            object.
          default: XRP

    IssuedCurrency:
      $id: IssuedCurrency
      type: object
      properties:
        currency:
          type: string
          description: 'Arbitrary currency code for the token.'
        issuer:
          type: string
          description: 'Generally, the account that issues this token. In special cases, this can refer to the account that holds the token instead (for example, in a Clawback transaction).'
          x-custom-validation:
            isAccount: true

    XChainBridge:
      $id: XChainBridge
      type: object
      description: |
        The bridge to create accounts for.
      required:
        - IssuingChainDoor
        - IssuingChainIssue
        - LockingChainDoor
        - LockingChainIssue
      properties:
        IssuingChainDoor:
          type: string
          description: |
            The door account on the issuing chain. For an XRP-XRP bridge, this must be the genesis account
            (the account that is created when the network is first started, which contains all of the XRP).
        IssuingChainIssue:
          $ref: '#/components/schemas/Currency'
          description: |
            The asset that is minted and burned on the issuing chain. For an IOU-IOU bridge, the issuer of
            the asset must be the door account on the issuing chain, to avoid supply issues.
        LockingChainDoor:
          type: string
          description: |
            The door account on the locking chain.
        LockingChainIssue:
          $ref: '#/components/schemas/Currency'
          description: |
            The asset that is locked and unlocked on the locking chain.

    NFTokenOffer:
      type: object
      properties:
        amount:
          oneOf:
            - type: string
              description: 'The amount of XRP (drops), represented as a string.'
              x-custom-validation:
                isNumericString: true
            - $ref: '#/components/schemas/TokenAmount'
        flags:
          type: integer
          description: >
            A set of bit-flags for this offer. See NFTokenOffer flags for possible values.
        nft_offer_index:
          type: string
          description: The ledger object ID of this offer.
        owner:
          type: string
          description: The account that placed this offer.
          x-custom-validation:
            isAccount: true

    ServerState:
      type: string
      description: >
        A string indicating to what extent the server is participating in the network.
        See [Possible Server States](https://xrpl.org/docs/references/http-websocket-apis/api-conventions/rippled-server-states) for more details.
      enum:
        - disconnected
        - connected
        - syncing
        - tracking
        - full
        - validating
        - propsing
      x-enum-descriptions:
        disconnected: The server is not connected to the XRP Ledger peer-to-peer network whatsoever. It may be running in offline mode, or it may not be able to access the network for whatever reason.
        connected: The server believes it is connected to the network.
        syncing: The server is currently behind on ledger versions. (It is normal for a server to spend a few minutes catching up after you start it.)
        tracking: The server is in agreement with the network.
        full: The server is fully caught-up with the network and could participate in validation, but is not doing so (possibly because it has not been configured as a validator).
        validating: The server is currently participating in validation of the ledger.
        propsing: The server is participating in validation of the ledger and currently proposing its own version.

    StateAccountingInfo:
      type: object
      properties:
        duration_us:
          type: string
          description: >
            The number of microseconds the server has spent in this state. (This is updated whenever the server transitions into another state.)
        transitions:
          type: string
          description: The number of times the server has changed into this state.

    StateAccounting:
      type: object
      description: >
        A map of various [server states](https://xrpl.org/docs/references/http-websocket-apis/api-conventions/rippled-server-states) with information about the time the server spends in each.
        This can be useful for tracking the long-term health of your server's connectivity to the network.
      properties:
        disconnected:
          $ref: '#/components/schemas/StateAccountingInfo'
        connected:
          $ref: '#/components/schemas/StateAccountingInfo'
        syncing:
          $ref: '#/components/schemas/StateAccountingInfo'
        tracking:
          $ref: '#/components/schemas/StateAccountingInfo'
        full:
          $ref: '#/components/schemas/StateAccountingInfo'
        validating:
          $ref: '#/components/schemas/StateAccountingInfo'
        proposing:
          $ref: '#/components/schemas/StateAccountingInfo'
